services:
    app:
        build: ./docker/php
        image: cfc
        container_name: cfc-app
        working_dir: /usr/src
        volumes:
            - .:/usr/src

    nginx:
        image: nginx:stable-alpine
        container_name: cfc-nginx
        working_dir: /usr/src
        ports:
            - "8000:80"
        volumes:
            - .:/usr/src
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf

    db:
        image: mysql:latest
        container_name: cfc-mysql
        working_dir: /usr/src
        volumes:
            - .mysqldata:/var/lib/mysql
        ports:
            - "${DB_PORT}:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
